# -*- coding: utf-8 -*-
"""Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MVsA3rWFbdPBtI1CqVGVTqtLfFbl9RNG
"""

from google.colab import files
files.upload()

# Commented out IPython magic to ensure Python compatibility.
#import trio 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

!pip install pycaret

#import pycaret
from pycaret.classification import setup, models, compare_models, predict_model

data = pd.read_csv("glass.csv")

data

data.info()

data.isna().sum()

"""#### No missing values

## Visualization
"""

plt.figure(figsize=(12,12))
plt.pie(data['Type'].value_counts(), labels=data['Type'].value_counts().index)
plt.title('Class Distribution')
plt.show()

"""## Setup, it is like pipeline where we can pass peprocessing and transformation steps."""

setup(
       data = data,
       target = 'Type', #target meaning the target feature
       normalize = True,
       train_size = 0.7
)

models()

best_model = compare_models()

"""### Extra Trees Classifier and Random Forest are better as shwon by PyCaret."""

best_model

predict_model(best_model)

